# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDo
  pod 'SwiftLint'

  target 'ToDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
